### ISSUE TITLE
.Work.Searcher: Start() 

### ISSUE THREAD

**Issue by os092** [Yegorich555/AliSearcher#4]
everytime i am trying to search its stop work and give me 

Error Engine.Work.Searcher: Start()
Not all goods loaded ( items doesn't successfull).
![image](https://user-images.githubusercontent.com/44339014/47266885-20875580-d545-11e8-8d7f-53c19f0adcf7.png)

**Comment by Yegorich555** [comment]
This interesting... Commonly this exception means that we don't have a correct html-page-reading. Reason for this is html page structure was changed. But I checked it on my PC and this works fine. You can set a breakpoint into line and take the real html-page. I think it can provide more info
